### ISSUE TITLE
Duplicate naming

### ISSUE THREAD

**Issue by teemulehtinen** [Aalto-LeTech/mooc-grader#18]
https://github.com/Aalto-LeTech/mooc-grader/blob/3e1585b23d16ec6d6b638836acd6922b57adb5c8/util/export.py#L63
In exercise configuration, the field "template" is used in many exercise types to override the default rendering template of the exercise view. However, at the commented location, the same field name "template" is expected to offer an URL that provides a code template for student to work on. This is currently confusing students in an exercise where template is used to set the rendering template but it has a side effect that adds a button "Show exercise template" with a broken link in the a-plus.

**Comment by matiaslindgren** [comment]
Seems to be working now at least locally in a trivial course containing an exercise with both exercise templates and a custom exercise view defined with the template keyword.
