### ISSUE TITLE
Warn / print something if feedback_template doesn't render anything.

### ISSUE THREAD

**Issue by raphendyr** [Aalto-LeTech/mooc-grader#24]
PR #19 introduced support for feedback templates in docker pipeline. This of course broke things where `feedback_template` was left from before and none noticed it wasn't doing anything. Thus, currently feedback is lost if invalid rendered is used.

So, we should check if feedback rendering actually creates any output, if not, then we should add debug explanation. In place of feedback (probably good idea as the output is so broken) or in the errors field that is visible only to course staff.

**Comment by Mankro** [comment]
Is anyone working on this yet?

**Comment by raphendyr** [comment]
I'm pretty sure that none is. I added this so I remember before making next production release :)
